import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {days} from '../site/itinerary.js';
const v=JSON.parse(await readFile('site/data/venues.json'));const ids=v.map(x=>x.id);assert.equal(new Set(ids).size,ids.length);assert.equal(ids.length,45);
const originals='bacchanal brothers-food-mart cafe-du-monde cake-cafe central-grocery coops-place dooky-chase elizabeths horns johnnys-po-boys jacques-imos mimis napoleon-house pizza-delicious port-of-call satsuma st-roch-market turkey-and-the-wolf verti-marte willie-maes spotted-cat three-muses dba maison dragons-den royal-street preservation-hall maple-leaf witches-brew frenchmen-art-market french-market euclid-records faulkner-house vaughans lafittes old-absinthe-house cane-table country-club bjs-lounge snake-jakes'.split(' ');assert.equal(originals.length,40);for(const id of originals)assert.ok(ids.includes(id),'Missing original: '+id);
for(const x of v){for(const field of ['id','name','category','area','address','hours','bestTime','order','tip','status','statusNote','schedule','originalNote','sources','checkedOn'])assert.ok(x[field],x.id+' missing '+field);assert.ok(Number.isFinite(x.lat)&&Number.isFinite(x.lng));assert.ok(x.sources.length);for(const s of x.sources)assert.ok(['http:','https:'].includes(new URL(s.url).protocol));}
assert.equal(days.length,6);days.forEach((d,i)=>{assert.equal(d.date,14+i);assert.equal(new Date(Date.UTC(2026,9,d.date)).toLocaleDateString('en-US',{weekday:'short',timeZone:'UTC'}).toUpperCase(),d.dow);for(const id of [...d.route,...d.alternatives,...d.stops.flatMap(s=>[s.venue,...(s.extra||[])].filter(Boolean))])assert.ok(ids.includes(id),id);assert.ok(d.stops.every(s=>!s.venue||v.find(x=>x.id===s.venue).status!=='closed'));});
assert.equal(days[4].stops[1].title,'Plantation & swamp tour');assert.ok(!days[4].route.includes('city-park'));
const map=JSON.parse(await readFile('site/data/map.json'));assert.ok(map.roads.length>1000);assert.ok(map.water.some(w=>w.kind==='riverbank'));for(const geom of [...map.roads,...map.water])for(const p of geom.points)assert.ok(p.length===2&&p.every(Number.isFinite));
const m=JSON.parse(await readFile('dist/offline-manifest.json'));for(const f of m.files.filter(f=>f!=='./'))assert.ok((await stat('dist/'+f)).size>0,f);
const html=await readFile('dist/index.html','utf8');for(const match of html.matchAll(/(?:href|src)="(\.\/[^"]+)"/g))assert.ok((await stat('dist/'+match[1])).isFile(),match[1]);
console.log('Passed: 45 venue records, all 40 originals, dates/weekdays, day links, Sunday tour, map geometry, offline asset completeness and HTML entry references.');
